version: '3'
services:
  db:
    image: postgres
    restart: always
    networks:
      - my_network
    env_file:
      - .env
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=mydb
      - POSTGRES_PORT=5432

  backend:
    build: ./backend
    networks:
      - my_network
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=123456
      - DB_NAME=mydb
      - DB_PORT=5432

  frontend:
    build: ./frontend
    networks:
      - my_network

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/usr/share/nginx/html
    ports:
      - "8080:80"
    depends_on:
      - frontend
    networks:
      - my_network

networks:
  my_network:
